
services:
  api:
    build: .
    container_name: mi_api_bun
    ports:
      - "80:3000" # Mapea el puerto 80 del servidor al 3000 del contenedor
    environment:
      - NODE_ENV=production
    restart: always

 